name: CI & Deploy

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Prepare lowercase vars
        run: |
          ACTOR_LOWER="${GITHUB_ACTOR,,}"
          REPO="${GITHUB_REPOSITORY##*/}"
          echo "LOWER_ACTOR=$ACTOR_LOWER" >> $GITHUB_ENV
          echo "LOWER_REPO=${REPO,,}"   >> $GITHUB_ENV
          
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.LOWER_ACTOR }}/${{ env.LOWER_REPO }}:latest .
      - name: Push to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.LOWER_ACTOR }}
          password: ${{ secrets.CR_PAT }}
      - name: Push image
        run: |
          docker push ghcr.io/${{ env.LOWER_ACTOR }}/${{ env.LOWER_REPO }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
   
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: PR9 
        images: ghcr.io/${{ env.LOWER_ACTOR }}/${{ env.LOWER_REPO }}:latest

