name: Build and Publish Docker Image

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase owner & repo names
        id: vars
        run: |
          echo "repo_lower=$(echo '${{ github.event.repository.name }}' \
            | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "owner_lower=$(echo '${{ github.repository_owner }}' \
            | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.vars.outputs.repo_lower }}:latest
